"use client";

import { FormEvent, useState } from "react";
import type { Locale } from "@/lib/types";

export function RightsForm({ locale = "zh" }: { locale?: Locale }) {
  const [fileName, setFileName] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (event.currentTarget.checkValidity()) { setSubmitted(true); event.currentTarget.reset(); setFileName(""); } };
  if (submitted) return <div role="status" className="border border-gold/40 bg-gold/5 p-7"><p className="font-serif text-2xl text-paper">{locale === "zh" ? "演示提交已完成" : "Demonstration submission complete"}</p><p className="mt-3 text-sm leading-7 text-muted">{locale === "zh" ? "本初版不会上传文件或发送通知。正式上线时需接入安全的邮件或工单后端，并将版权邮箱替换为真实地址。" : "No file was uploaded and no notice was sent. Connect a secure mail or ticket backend and replace the demonstration address before launch."}</p><button type="button" onClick={() => setSubmitted(false)} className="button-secondary mt-5">{locale === "zh" ? "填写另一份通知" : "Start another notice"}</button></div>;
  return <form onSubmit={submit} className="mt-10 grid gap-6" aria-label={locale === "zh" ? "版权问题报告表单" : "Rights concern form"}>
    <div className="grid gap-6 sm:grid-cols-2"><label className="text-sm text-muted">{locale === "zh" ? "姓名或机构名称" : "Name or organization"} <span className="text-gold">*</span><input name="name" required maxLength={80} className="form-field mt-2" autoComplete="name" /></label><label className="text-sm text-muted">{locale === "zh" ? "联系邮箱" : "Contact email"} <span className="text-gold">*</span><input name="email" required type="email" className="form-field mt-2" autoComplete="email" /></label></div>
    <label className="text-sm text-muted">{locale === "zh" ? "涉及页面链接" : "Page URL"} <span className="text-gold">*</span><input name="url" required type="url" placeholder="https://…" className="form-field mt-2" /></label>
    <div className="grid gap-6 sm:grid-cols-2"><label className="text-sm text-muted">{locale === "zh" ? "权利类型" : "Type of right"} <span className="text-gold">*</span><select name="rightType" required defaultValue="" className="form-field mt-2"><option value="" disabled>{locale === "zh" ? "请选择" : "Select"}</option>{(locale === "zh" ? ["著作权", "肖像权", "商标权", "合法授权代表", "其他合法权益"] : ["Copyright", "Publicity / likeness", "Trademark", "Authorized representative", "Other legal right"]).map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm text-muted">{locale === "zh" ? "希望采取的处理方式" : "Requested action"} <span className="text-gold">*</span><select name="action" required defaultValue="" className="form-field mt-2"><option value="" disabled>{locale === "zh" ? "请选择" : "Select"}</option>{(locale === "zh" ? ["暂时隐藏", "补充或更正授权信息", "删除相关内容", "联系我进一步核验"] : ["Temporarily hide", "Correct rights information", "Remove the content", "Contact me for verification"]).map((item) => <option key={item}>{item}</option>)}</select></label></div>
    <label className="text-sm text-muted">{locale === "zh" ? "问题说明" : "Description"} <span className="text-gold">*</span><textarea name="description" required minLength={20} maxLength={2000} rows={7} className="form-field mt-2 resize-y" placeholder={locale === "zh" ? "请说明您拥有的权利、涉及内容及具体问题（至少20字）" : "Describe your rights, the content involved and the requested resolution (minimum 20 characters)"} /></label>
    <label className="text-sm text-muted">{locale === "zh" ? "权属证明" : "Evidence of rights"} <span className="text-gold">*</span><input name="proof" required type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? "")} className="form-field mt-2 file:mr-4 file:border-0 file:bg-gold file:px-3 file:py-2 file:text-ink" /><span className="mt-2 block text-xs text-muted">{locale === "zh" ? "演示环境只显示文件名，不会上传或保存文件。支持PDF/JPG/PNG。" : "This demonstration shows the file name only. It does not upload or store files. PDF/JPG/PNG."}</span>{fileName && <span className="mt-2 block text-xs text-gold">{locale === "zh" ? "已选择" : "Selected"}：{fileName}</span>}</label>
    <label className="flex items-start gap-3 text-sm leading-6 text-muted"><input required type="checkbox" className="mt-1 h-4 w-4 accent-[#C69A5B]" /><span>{locale === "zh" ? "我确认所填信息真实，并同意本站为核验本通知而处理这些信息。" : "I confirm that this information is accurate and consent to its processing for verification."}<span className="text-gold"> *</span></span></label>
    <div><button type="submit" className="button-primary">{locale === "zh" ? "提交演示通知" : "Submit demonstration notice"}</button><p className="mt-3 text-xs text-gold">{locale === "zh" ? "注意：此按钮不会真实发送。正式上线前必须接入后端。" : "This button does not send anything. Connect a backend before launch."}</p></div>
  </form>;
}
