import type { CopyrightInfo, Frame } from "./types";

const originalCopyright = (title: string): CopyrightInfo => ({
  imageTitle: title,
  author: "镜间视觉实验室",
  rightsHolder: "镜间演示项目",
  sourceUrl: "/copyright#original-demo-assets",
  sourceType: "镜间原创演示资产",
  licenseType: "本站内部演示授权",
  copyrightStatus: "本站原创",
  usageScope: "仅限镜间网站功能演示与电影美学分析，不作为商业素材授权",
  allowDownload: false,
  proofNote: "JJ-DEMO-2026 · 创作与审核记录留档",
  addedDate: "2026-09-05",
  reviewStatus: "审核通过",
});

const frame = (input: Omit<Frame, "copyright">): Frame => ({ ...input, copyright: originalCopyright(input.title) });

export const extendedFrames: Frame[] = [
  frame({
    slug: "teahouse-kettle", filmSlug: "southern-teahouse", title: "茶炉未熄", image: "/images/frames/teahouse-kettle.png",
    alt: "雨夜河畔茶馆内，旧铜壶在木柜上冒出蒸汽，远处站着无清晰面容的虚构人物",
    palette: ["#B17B3D", "#34565A", "#24231E", "#789092"], colors: ["暖黄", "冷蓝", "低饱和"], compositions: ["三分法", "纵深"], shotSize: "全景",
    lights: ["自然光", "低调光"], lightDirection: "右侧河面与上方吊灯", lightQuality: "雨天柔光与局部暖光", subjectPosition: "人物位于右侧后景", visualFocus: "左侧铜壶蒸汽与后景人影", scenes: ["茶馆", "雨夜"], moods: ["怀旧", "孤独"], time: "黄昏", region: "中国南方", decade: "2010年代",
    analysis: "铜壶被安排在近景最暗的木台上，蒸汽却接住吊灯暖光，先于人物成为可见的生命迹象。右侧人影退到湿冷河岸，尺度被门框和雨幕压小。画面把室内残留的温度与即将离开的身体放在同一纵深中，让“炉火未熄”成为关系尚未真正结束的暗示。",
  }),
  frame({
    slug: "teahouse-corridor", filmSlug: "southern-teahouse", title: "深廊尽头", image: "/images/frames/teahouse-corridor.png",
    alt: "旧茶馆层层木门形成深廊，尽头一名无清晰面容的虚构人物正在关门",
    palette: ["#9B713D", "#385653", "#211C17", "#697A70"], colors: ["暖黄", "绿色", "低饱和"], compositions: ["框架", "纵深"], shotSize: "远景",
    lights: ["自然光", "轮廓光"], lightDirection: "走廊尽头向镜头", lightQuality: "柔和环境光配合窄亮边", subjectPosition: "画面中心最远处", visualFocus: "重复门框包围的关门动作", scenes: ["茶馆"], moods: ["压抑", "孤独"], time: "黄昏", region: "中国南方", decade: "2010年代",
    analysis: "五层木门把原本不长的走廊拉成难以抵达的距离，人物在最末一层框架中只剩小小轮廓。近景暖色木料占据观看路径，远处雨光却偏冷，观众仿佛必须穿过一段旧日生活才能看见结束。关门动作没有被放大，反而因距离而显得不可挽回。",
  }),
  frame({
    slug: "teahouse-river-window", filmSlug: "southern-teahouse", title: "河水漫过窗沿", image: "/images/frames/teahouse-river-window.png",
    alt: "从昏暗茶馆透过两扇木窗看向雨中的河面，窗边留着一把空藤椅",
    palette: ["#617A75", "#2E4847", "#8B6D43", "#1A1A17"], colors: ["绿色", "冷蓝", "低饱和"], compositions: ["框架", "留白"], shotSize: "全景",
    lights: ["自然光", "逆光"], lightDirection: "窗外河面向室内", lightQuality: "阴天漫射柔光", subjectPosition: "画面无人，空椅位于右侧", visualFocus: "双窗之间的河面与空椅", scenes: ["茶馆", "自然景观"], moods: ["孤独", "怀旧"], time: "白天", region: "中国南方", decade: "2010年代",
    analysis: "两扇窗把同一条河切成彼此相邻却不连续的景象，中间粗重窗柱像一道无法跨越的停顿。右侧空椅保留了人的尺度，却没有人物出现，观众自然把雨水上涨理解为时间正在侵入室内。冷绿河面比木墙更亮，使离席不再是瞬间动作，而成为持续扩大的空缺。",
  }),
  frame({
    slug: "teahouse-empty-chair", filmSlug: "southern-teahouse", title: "被推开的椅子", image: "/images/frames/teahouse-empty-chair.png",
    alt: "茶馆小桌两侧放着旧木椅，其中一把椅子被推开，桌上茶水未动",
    palette: ["#AF8246", "#51402D", "#34433A", "#171512"], colors: ["暖黄", "低饱和"], compositions: ["对称", "倾斜"], shotSize: "中景",
    lights: ["侧光", "低调光"], lightDirection: "左侧窗缝", lightQuality: "窄幅柔侧光", subjectPosition: "画面无人，右椅偏离轴线", visualFocus: "被推开的椅脚与两杯冷茶", scenes: ["茶馆"], moods: ["压抑", "怀旧"], time: "夜晚", region: "中国南方", decade: "2010年代",
    analysis: "桌椅原本形成稳定对称，一把椅子向后斜开后，秩序便被一个很小的角度打破。桌上的两杯茶仍保持相对位置，暗示离开刚刚发生，器物还未来得及适应人的缺席。光线只触及桌缘与椅脚，空位比完整的人物表情更直接地说明谈话已经中断。",
  }),
  frame({
    slug: "teahouse-morning-steam", filmSlug: "southern-teahouse", title: "清晨第一笼蒸汽", image: "/images/frames/teahouse-morning-steam.png",
    alt: "清晨茶馆内竹蒸笼和白瓷杯升起蒸汽，半透明帘后有模糊的虚构人物剪影",
    palette: ["#C5AA75", "#82928A", "#4A5A52", "#29251E"], colors: ["暖黄", "绿色", "低饱和"], compositions: ["三分法", "框架"], shotSize: "近景",
    lights: ["自然光", "侧光"], lightDirection: "右侧清晨窗光", lightQuality: "低反差柔光", subjectPosition: "人物模糊在左侧后景", visualFocus: "前景蒸汽穿过窗光的层次", scenes: ["茶馆"], moods: ["温暖", "怀旧"], time: "清晨", region: "中国南方", decade: "2010年代",
    analysis: "蒸汽把清晨侧光变成可见的薄层，前景器物因此拥有比人物更清晰的触感。帘后身影没有被完全辨认，劳动只以轮廓进入画面，使开门营业显得像一种长期重复的记忆。暖灰与青绿彼此渗透，温暖并不来自热烈色彩，而来自空间重新开始运转。",
  }),

  frame({
    slug: "lane-bicycle", filmSlug: "after-the-rain-lane", title: "雨墙边的单车", image: "/images/frames/lane-bicycle.png",
    alt: "冷蓝雨巷里一辆旧单车靠在湿墙边，远处无清晰面容的撑伞人物转过街角",
    palette: ["#173341", "#47636A", "#8C5B43", "#0D151A"], colors: ["冷蓝", "低饱和"], compositions: ["三分法", "纵深"], shotSize: "全景",
    lights: ["自然光", "低调光"], lightDirection: "巷道后方路灯", lightQuality: "雨雾扩散的柔光", subjectPosition: "人物位于右侧远景", visualFocus: "左侧单车与远处转角", scenes: ["街道", "雨夜"], moods: ["孤独", "神秘"], time: "夜晚", region: "中国东部", decade: "2020年代",
    analysis: "单车占据前景却无人骑乘，潮湿金属表面接住微弱蓝光，成为一段被暂停的行动。远处撑伞身影即将消失在转角，透视线把两者连接起来，却没有证明它们属于同一个人。画面让观众在遗留物与离去者之间建立猜测，空巷因此获得调查现场般的安静。",
  }),
  frame({
    slug: "lane-bus-stop", filmSlug: "after-the-rain-lane", title: "末班车之后", image: "/images/frames/lane-bus-stop.png",
    alt: "雨夜空公交亭的玻璃布满水痕，远处有一名无清晰面容的虚构人物独自走来",
    palette: ["#244759", "#78939A", "#B78951", "#10181E"], colors: ["冷蓝", "暖黄", "低饱和"], compositions: ["框架", "留白"], shotSize: "全景",
    lights: ["侧光", "自然光"], lightDirection: "街道左后方与对面窗口", lightQuality: "被雨水折射的柔光", subjectPosition: "人物位于左侧远景", visualFocus: "空长椅与玻璃后的孤立身影", scenes: ["街道", "雨夜", "车站"], moods: ["孤独", "压抑"], time: "夜晚", region: "中国东部", decade: "2020年代",
    analysis: "玻璃框架把公交亭分成数个透明隔间，空长椅却横贯其中，强调等待本应属于多人。人物被留在亭外远处，蓝色路灯拉长脚下反光，使靠近的动作显得缓慢。对面唯一暖窗没有形成邀请，只在雨幕中提示另一个无法进入的室内世界，等待因此转为被城市搁置。",
  }),
  frame({
    slug: "lane-shutter", filmSlug: "after-the-rain-lane", title: "卷帘门前", image: "/images/frames/lane-shutter.png",
    alt: "旧城雨巷中关闭的金属卷帘门前放着一把折伞，红光倒影斜穿积水",
    palette: ["#153146", "#963F38", "#4D5760", "#0B1117"], colors: ["冷蓝", "红色", "高对比"], compositions: ["倾斜", "三分法"], shotSize: "中景",
    lights: ["霓虹", "侧光"], lightDirection: "画外右侧店面", lightQuality: "硬光经积水反射", subjectPosition: "画面无人，折伞位于左下", visualFocus: "斜向红色倒影与关闭的门", scenes: ["街道", "雨夜"], moods: ["紧张", "神秘"], time: "夜晚", region: "中国东部", decade: "2020年代",
    analysis: "卷帘门的水平纹理建立封闭而重复的秩序，积水中的红光却以斜线切断它，像一个仍在移动的危险信号。折伞被留在低处暗部，没有人物解释它为何出现。画面把“关闭”与“遗留”并置，让普通店面成为事件之后的痕迹，观众的注意力不断在门与伞之间往返。",
  }),
  frame({
    slug: "lane-crossing", filmSlug: "after-the-rain-lane", title: "穿过交叉口", image: "/images/frames/lane-crossing.png",
    alt: "俯视雨夜小城交叉口，一名无清晰面容的撑伞人物从红蓝倒影之间穿过",
    palette: ["#17384B", "#A3443E", "#517789", "#0A1118"], colors: ["冷蓝", "红色", "高对比"], compositions: ["倾斜", "留白"], shotSize: "远景",
    lights: ["霓虹", "逆光"], lightDirection: "街口两侧画外光源", lightQuality: "雾化硬光", subjectPosition: "人物位于下方三分线", visualFocus: "人物经过的冷暖交界", scenes: ["街道", "雨夜"], moods: ["紧张", "孤独"], time: "夜晚", region: "中国东部", decade: "2020年代",
    analysis: "高机位把人物缩成路口几何中的一个移动点，斜向道路没有提供稳定的前进方向。红蓝倒影在他脚下交汇，既像两条可选路径，也像两种互相冲突的记忆。大片无人路面让穿越动作显得暴露，观众先感到环境的压力，之后才意识到人物必须独自作出方向判断。",
  }),
  frame({
    slug: "lane-phone-booth", filmSlug: "after-the-rain-lane", title: "没有接通的电话", image: "/images/frames/lane-phone-booth.png",
    alt: "雨夜旧玻璃电话亭内听筒微微垂下，亭外有模糊的虚构人物剪影",
    palette: ["#1B3E4E", "#A97B44", "#546E70", "#101416"], colors: ["冷蓝", "暖黄", "低饱和"], compositions: ["框架", "三分法"], shotSize: "中景",
    lights: ["侧光", "低调光"], lightDirection: "电话亭内部顶灯", lightQuality: "局部柔光与深暗背景", subjectPosition: "人物位于亭外左侧后景", visualFocus: "玻璃框中的悬垂听筒", scenes: ["街道", "雨夜"], moods: ["孤独", "神秘"], time: "夜晚", region: "中国东部", decade: "2020年代",
    analysis: "电话亭内部比街道更暖，却空无一人，悬垂听筒让缺席带上刚刚发生的时间感。玻璃上的水痕把亭外身影分割成模糊色块，观众无法判断他是在靠近还是离开。左侧大片冷暗墙面没有信息，进一步把电话亭孤立成一段未完成的交流，而不是安全的避雨处。",
  }),

  frame({
    slug: "train-sleeper", filmSlug: "night-train", title: "下铺的空位", image: "/images/frames/train-sleeper.png",
    alt: "夜行列车卧铺隔间里被褥整齐，帘后只露出虚构乘客的鞋，没有清晰面容",
    palette: ["#243D48", "#6B7666", "#9A8E70", "#11161B"], colors: ["冷蓝", "绿色", "低饱和"], compositions: ["框架", "纵深"], shotSize: "中景",
    lights: ["侧光", "低调光"], lightDirection: "左侧车窗移动光", lightQuality: "间歇硬侧光", subjectPosition: "人物只以鞋出现在下铺边缘", visualFocus: "整齐空铺与帘下的鞋", scenes: ["列车"], moods: ["神秘", "紧张"], time: "夜晚", region: "中国北方", decade: "2010年代",
    analysis: "整齐铺位提供了可以躺下的安全暗示，帘下露出的鞋却证明隔间并非真正无人。窗口移动光只扫过床单，刻意避开藏在帘后的身体，使可见信息与人物存在发生冲突。门框和床架组成多重矩形，观众像站在过道偷看，秘密感来自观看位置本身，而非戏剧动作。",
  }),
  frame({
    slug: "train-dining-car", filmSlug: "night-train", title: "两端的乘客", image: "/images/frames/train-dining-car.png",
    alt: "昏暗夜车餐车里两名无清晰面容的虚构乘客分坐远端，近桌留着两只空杯",
    palette: ["#253B39", "#59695A", "#8E895F", "#0F1211"], colors: ["绿色", "冷蓝", "低饱和"], compositions: ["对称", "纵深"], shotSize: "全景",
    lights: ["低调光", "自然光"], lightDirection: "顶部荧光灯与两侧车窗", lightQuality: "平直弱光配合深暗部", subjectPosition: "两人分列画面左右远端", visualFocus: "中央过道和近景两只空杯", scenes: ["列车", "餐厅"], moods: ["压抑", "神秘"], time: "夜晚", region: "中国北方", decade: "2010年代",
    analysis: "餐车的桌椅重复形成规则节拍，两名乘客却被放在相反方向，距离被整条过道放大。近景两只空杯暗示本应发生的会面，却比人物更靠近观众。顶部绿光维持公共空间的冷静，窗外深蓝不断移动，让静止对坐带有列车正在替他们推进、关系却停在原地的矛盾。",
  }),
  frame({
    slug: "train-tunnel", filmSlug: "night-train", title: "隧道掠光", image: "/images/frames/train-tunnel.png",
    alt: "列车进入隧道时一道亮光掠过虚构乘客的手与外套，人物面部不在画面中",
    palette: ["#162A35", "#667A78", "#B8A77C", "#0B0F14"], colors: ["冷蓝", "高对比"], compositions: ["倾斜", "框架"], shotSize: "特写",
    lights: ["侧光", "低调光"], lightDirection: "车窗外横向移动", lightQuality: "短促硬光", subjectPosition: "双手位于右下三分区", visualFocus: "光带越过紧握的手指", scenes: ["列车"], moods: ["紧张", "神秘"], time: "夜晚", region: "中国北方", decade: "2010年代",
    analysis: "人物面部被完全排除，短促光带只揭示紧握的双手和粗糙衣料，让情绪变成身体压力。倾斜窗框与横向掠光形成相反方向，静止特写因此仍有速度感。隧道黑暗吞没其余空间，观众只能在每次亮起的瞬间收集证据，信息控制直接模拟了秘密被断续透露的过程。",
  }),
  frame({
    slug: "train-luggage", filmSlug: "night-train", title: "未合上的行李", image: "/images/frames/train-luggage.png",
    alt: "夜车行李架上一只无品牌旧箱微微打开，缝隙中露出没有文字的折纸",
    palette: ["#4A574D", "#75634A", "#2A3233", "#111513"], colors: ["绿色", "低饱和"], compositions: ["倾斜", "三分法"], shotSize: "近景",
    lights: ["低调光", "侧光"], lightDirection: "车厢顶部左侧", lightQuality: "窄幅硬光", subjectPosition: "画面无人，行李位于上方三分线", visualFocus: "箱盖缝隙中的白色折纸", scenes: ["列车"], moods: ["神秘", "紧张"], time: "夜晚", region: "中国北方", decade: "2010年代",
    analysis: "低机位让行李架压在观众头顶，倾斜金属线条把注意力引向唯一没有合拢的箱子。纸张亮度远高于周围旧布和暗绿车厢，因此即使面积很小，也像一句突然出现的提示。画面不展示主人，只让物体违反整齐秩序，悬念便来自“谁留下了这个开口”。",
  }),
  frame({
    slug: "train-station-clock", filmSlug: "night-train", title: "站台停在两点", image: "/images/frames/train-station-clock.png",
    alt: "从夜车门框望向雾中空站台和无文字圆钟，一名虚构列车员背对镜头",
    palette: ["#37505A", "#788486", "#A88C59", "#151A1C"], colors: ["冷蓝", "低饱和"], compositions: ["框架", "中心"], shotSize: "全景",
    lights: ["轮廓光", "低调光"], lightDirection: "站台顶灯与车厢门内", lightQuality: "雾中扩散点光", subjectPosition: "人物位于中央下方", visualFocus: "高处圆钟与人物背影", scenes: ["车站", "列车"], moods: ["孤独", "神秘"], time: "夜晚", region: "中国北方", decade: "2010年代",
    analysis: "车门把站台压缩成一幅冷色画框，列车员站在几何中心，却因雾与空旷显得没有权力。高处圆钟与他的背影构成垂直关系，观看先确认时间，再寻找人是否准备行动。车厢暖光停在门槛内，没有真正抵达站台，使停靠像一次短暂但无法进入的现实。",
  }),

  frame({
    slug: "summer-rooftop-water", filmSlug: "humid-summer", title: "屋顶积水", image: "/images/frames/summer-rooftop-water.png",
    alt: "海边小城晒白的屋顶留着浅积水和晾衣绳，水面映出大片白云",
    palette: ["#BFC9C4", "#75A6A8", "#D7D0B3", "#7A866E"], colors: ["冷蓝", "低饱和"], compositions: ["留白", "三分法"], shotSize: "全景",
    lights: ["自然光", "逆光"], lightDirection: "高处云后日光", lightQuality: "明亮散射光", subjectPosition: "画面无人", visualFocus: "屋顶浅水中的云层倒影", scenes: ["自然景观"], moods: ["温暖", "怀旧"], time: "白天", region: "中国沿海", decade: "2020年代",
    analysis: "低地平线把天空扩展为主要画面，屋顶积水又复制了一层云，使空间在上下之间短暂失去重量。没有人物的晾衣绳仍保留生活痕迹，风让它成为唯一运动。日晒白与淡青降低了视觉压力，画面没有直接表达快乐，而是以雨后短暂清亮提示青春中难得的停顿。",
  }),
  frame({
    slug: "summer-arcade", filmSlug: "humid-summer", title: "正午骑楼", image: "/images/frames/summer-arcade.png",
    alt: "海边小城骑楼在正午形成深长阴影，远处两名无清晰面容的虚构少年并肩站立",
    palette: ["#B7BEA0", "#62837B", "#F0E3C2", "#3A4A43"], colors: ["绿色", "暖黄", "低饱和"], compositions: ["纵深", "对称"], shotSize: "远景",
    lights: ["自然光", "侧光"], lightDirection: "柱廊外侧强烈日光", lightQuality: "硬光与反射柔光并存", subjectPosition: "人物位于远端中央", visualFocus: "柱列尽头的两个人影", scenes: ["街道"], moods: ["怀旧", "温暖"], time: "白天", region: "中国沿海", decade: "2020年代",
    analysis: "重复方柱把正午阴影切成一段段凉处，视线沿着地面亮暗节奏抵达远端少年。人物很小，却因居于透视中心而保持联系；他们没有面向镜头，关系由并肩距离而非表情说明。外部白光几乎过曝，内部绿色反光则柔和黏稠，酷热因此通过空间对比被身体化。",
  }),
  frame({
    slug: "summer-kitchen", filmSlug: "humid-summer", title: "停电后的西瓜", image: "/images/frames/summer-kitchen.png",
    alt: "停电的沿海小城厨房里，搪瓷桌上放着切开的西瓜，窗帘在热空气中静止",
    palette: ["#6F8A72", "#C85E4B", "#D5C8A8", "#343E38"], colors: ["绿色", "红色", "低饱和"], compositions: ["三分法", "留白"], shotSize: "中景",
    lights: ["自然光", "侧光"], lightDirection: "右侧开放窗户", lightQuality: "沉重的午后柔光", subjectPosition: "画面无人", visualFocus: "桌上红色瓜瓤与静止窗帘", scenes: ["餐厅", "卧室"], moods: ["温暖", "压抑"], time: "白天", region: "中国沿海", decade: "2020年代",
    analysis: "西瓜红成为低饱和绿灰空间中唯一鲜明颜色，先唤起清凉期待，也暴露空气的闷热。窗帘完全静止，风扇和电器都沉入暗处，画面用没有运动的布料表现停电。桌面留着切开的食物却无人出现，家庭日常像被高温暂时按下暂停，温暖与压抑同时成立。",
  }),
  frame({
    slug: "summer-empty-pool", filmSlug: "humid-summer", title: "枯水泳池", image: "/images/frames/summer-empty-pool.png",
    alt: "海边废弃的淡蓝泳池已经排空，只在角落积着雨水并留下一只旧球",
    palette: ["#8DB2B4", "#C8C7B8", "#657C69", "#8D8062"], colors: ["冷蓝", "低饱和"], compositions: ["倾斜", "留白"], shotSize: "全景",
    lights: ["自然光"], lightDirection: "均匀阴天天光", lightQuality: "低反差柔光", subjectPosition: "画面无人", visualFocus: "空池底部孤立的球", scenes: ["自然景观"], moods: ["孤独", "怀旧"], time: "白天", region: "中国沿海", decade: "2020年代",
    analysis: "泳池本应容纳水与身体，如今只剩褪色边界和一小片脏水，功能缺失直接转化为空间情绪。斜向池沿把目光引到右下角的旧球，它以很小尺度保留过去活动的证据。阴天柔光没有制造戏剧阴影，反而让废弃状态显得普通而持续，像夏天尚未结束，童年却已提前退场。",
  }),
  frame({
    slug: "summer-storm-window", filmSlug: "humid-summer", title: "暴雨抵达窗前", image: "/images/frames/summer-storm-window.png",
    alt: "沿海卧室窗帘被暴雨前的风吹起，一只虚构人物的手伸向窗扣，面部不在画面中",
    palette: ["#68847A", "#A8B2A7", "#D2C5A5", "#394540"], colors: ["绿色", "冷蓝", "低饱和"], compositions: ["框架", "倾斜"], shotSize: "近景",
    lights: ["自然光", "逆光"], lightDirection: "窗外暴雨云层", lightQuality: "快速变暗的柔逆光", subjectPosition: "手位于右侧边缘", visualFocus: "鼓起的窗帘与即将合窗的手", scenes: ["卧室", "雨夜"], moods: ["紧张", "怀旧"], time: "黄昏", region: "中国沿海", decade: "2020年代",
    analysis: "窗帘突然鼓起，把不可见的风变成画面最大动作；伸出的手尚未碰到窗扣，事件停在即将发生之前。室外绿光比室内更亮，却带着暴雨前的灰度，开放窗口因此既像邀请也像威胁。桌边录音设备被压在暗部，暗示人物想保存声音，却必须先对抗正在闯入的天气。",
  }),

  frame({
    slug: "hill-cable-car", filmSlug: "letters-from-hill-city", title: "雾中缆车", image: "/images/frames/hill-cable-car.png",
    alt: "无具体地标的虚构山城被清晨雾气覆盖，一辆小缆车沿斜线穿过层叠屋顶",
    palette: ["#879291", "#985F4B", "#4F5F59", "#333A3A"], colors: ["低饱和", "绿色"], compositions: ["倾斜", "纵深"], shotSize: "远景",
    lights: ["自然光"], lightDirection: "雾层后的清晨天光", lightQuality: "均匀漫射柔光", subjectPosition: "画面无人，缆车位于左侧三分线", visualFocus: "穿过城市层次的斜向缆索", scenes: ["街道", "自然景观"], moods: ["怀旧", "孤独"], time: "清晨", region: "中国西南", decade: "2010年代",
    analysis: "缆索以清晰斜线穿过被雾消解的建筑层次，成为画面中唯一确定的方向。缆车体量很小，却因颜色比背景稍暖而保持可读，像一封缓慢移动的信。远处屋顶失去边界，让目的地无法被准确判断；行进因此不等于接近，只说明某种日常坚持仍在城市中持续。",
  }),
  frame({
    slug: "hill-rooftop-lines", filmSlug: "letters-from-hill-city", title: "电线切过山城", image: "/images/frames/hill-rooftop-lines.png",
    alt: "层叠山城屋顶上方交错着电线，一名无清晰面容的虚构邮差背对镜头站在露台",
    palette: ["#7B8582", "#A16B50", "#4C4742", "#C0A77E"], colors: ["低饱和", "暖黄"], compositions: ["倾斜", "纵深"], shotSize: "远景",
    lights: ["侧光", "自然光"], lightDirection: "左侧傍晚低阳", lightQuality: "雾中柔化侧光", subjectPosition: "人物位于下方三分线", visualFocus: "交错电线与邮差行进方向", scenes: ["街道"], moods: ["孤独", "怀旧"], time: "黄昏", region: "中国西南", decade: "2010年代",
    analysis: "电线在前景形成复杂交叉，既描绘山城密度，也像把人物的路线提前切成许多选择。邮差背影很小，暖侧光只擦过肩部和砖墙，使他暂时从灰雾中分离。层层屋顶没有明确地面，观众难以判断高低关系，送信于是被理解为持续穿越结构，而不只是抵达一个地址。",
  }),
  frame({
    slug: "hill-postbox", filmSlug: "letters-from-hill-city", title: "墙里的旧邮箱", image: "/images/frames/hill-postbox.png",
    alt: "潮湿山城楼梯墙面嵌着无标志的旧红邮箱，箱盖下压着一封没有文字的信",
    palette: ["#8F5044", "#777B72", "#4A5A4D", "#2C302E"], colors: ["红色", "低饱和"], compositions: ["三分法", "纵深"], shotSize: "近景",
    lights: ["自然光", "侧光"], lightDirection: "楼梯上方左侧", lightQuality: "阴天柔侧光", subjectPosition: "画面无人", visualFocus: "褪色红箱与夹住的白信封", scenes: ["街道"], moods: ["怀旧", "神秘"], time: "白天", region: "中国西南", decade: "2010年代",
    analysis: "褪色红邮箱从灰绿墙面中缓慢浮出，没有鲜艳到构成警报，却足以成为观看中心。白信封被夹在箱盖边缘，投递动作处于完成与失败之间。后方楼梯向上消失，提供了一条可能的来路，却没有人物现身；画面把叙事压缩到一个物体的异常状态，让等待显得具体而漫长。",
  }),
  frame({
    slug: "hill-stair-rain", filmSlug: "letters-from-hill-city", title: "雨中的上坡路", image: "/images/frames/hill-stair-rain.png",
    alt: "小雨中的陡峭山城石阶上，一名无清晰面容的虚构邮差撑伞背向镜头向上走",
    palette: ["#667675", "#93644F", "#3E4D46", "#B0ADA0"], colors: ["冷蓝", "低饱和"], compositions: ["倾斜", "纵深"], shotSize: "全景",
    lights: ["自然光", "轮廓光"], lightDirection: "石阶上方阴天天光", lightQuality: "雨雾柔光", subjectPosition: "人物位于中央偏上", visualFocus: "伞与连续上升的台阶", scenes: ["街道", "雨夜"], moods: ["孤独", "压抑"], time: "白天", region: "中国西南", decade: "2010年代",
    analysis: "石阶以强烈斜线占满画面，人物每向上一步，都显得仍被更长的道路压住。前景栏杆遮挡部分台阶，让观众无法一次看清完整路线，身体负担因此通过观看阻力被体验。雨雾降低背景反差，只保留伞和邮包的轮廓，角色不是城市主人，而是被复杂地形持续检验的人。",
  }),
  frame({
    slug: "hill-terrace-dusk", filmSlug: "letters-from-hill-city", title: "高台来信", image: "/images/frames/hill-terrace-dusk.png",
    alt: "虚构山城黄昏高台上放着空木椅与一叠无字信封，远处城市沉入蓝灰雾气",
    palette: ["#5C6D7B", "#C08655", "#705A4A", "#262B31"], colors: ["冷蓝", "暖黄", "低饱和"], compositions: ["留白", "三分法"], shotSize: "远景",
    lights: ["自然光", "侧光"], lightDirection: "左侧落日", lightQuality: "黄昏柔侧光", subjectPosition: "画面无人，空椅位于右侧前景", visualFocus: "信封、空椅与雾中城市的距离", scenes: ["自然景观"], moods: ["怀旧", "孤独"], time: "黄昏", region: "中国西南", decade: "2010年代",
    analysis: "空椅靠近镜头，信封放在低墙上，两个物体共同保留了一次无人赴约的规模。远处城市灯光逐渐亮起，却被蓝灰雾气压成细小光点，公共生活与前景私人等待相隔很远。黄昏暖色只停留在信纸边缘，没有覆盖整座城，使“来信”更像最后一束尚未消失的联系。",
  }),

  frame({
    slug: "cinema-projector-reel", filmSlug: "empty-cinema", title: "最后一卷胶片", image: "/images/frames/cinema-projector-reel.png",
    alt: "黑暗放映室内旧放映机和胶片盘被暖光照亮，边缘只出现虚构人物的手",
    palette: ["#A8753F", "#5A3B2D", "#272224", "#0B0A0B"], colors: ["暖黄", "高对比"], compositions: ["三分法", "倾斜"], shotSize: "特写",
    lights: ["侧光", "低调光"], lightDirection: "放映机灯门向右后方", lightQuality: "集中硬光与金属反射", subjectPosition: "人物仅以手出现在右侧边缘", visualFocus: "转动胶片盘与穿过尘埃的光束", scenes: ["放映厅"], moods: ["怀旧", "紧张"], time: "夜晚", region: "中国内陆", decade: "2020年代",
    analysis: "胶片盘占据画面左侧，圆形运动与斜向光束形成时间和方向两种节奏。人物只以手进入边缘，操作被看见，身份却退到黑暗中，使机器像真正的主角。暖光在金属划痕上闪烁，每一道痕迹都强调放映已经重复多年；最后一卷的终结因此带着劳动结束的重量。",
  }),
  frame({
    slug: "cinema-torn-curtain", filmSlug: "empty-cinema", title: "幕布缺口", image: "/images/frames/cinema-torn-curtain.png",
    alt: "空放映厅舞台的暗红幕布围住空白银幕，其中一侧幕布留下不规则缺口",
    palette: ["#6F2D2D", "#A1744A", "#342427", "#0D0C0E"], colors: ["红色", "低饱和"], compositions: ["对称", "中心"], shotSize: "全景",
    lights: ["低调光", "侧光"], lightDirection: "舞台侧后方工作灯", lightQuality: "微弱硬光", subjectPosition: "画面无人", visualFocus: "对称幕布中唯一不规则的破口", scenes: ["放映厅"], moods: ["压抑", "怀旧"], time: "夜晚", region: "中国内陆", decade: "2020年代",
    analysis: "舞台保持严格正面与对称，银幕也完全空白，空间原本具有仪式般的稳定。右侧幕布的缺口成为唯一偏差，边缘被工作灯勾亮，观看因此不断被拉离中心。暗红绒布吸收光线，使破损不像突发事故，更像长时间积累的衰败；秩序仍在，维护它的力量却已经离场。",
  }),
  frame({
    slug: "cinema-lobby-clock", filmSlug: "empty-cinema", title: "大堂时钟", image: "/images/frames/cinema-lobby-clock.png",
    alt: "废弃影院大堂的空售票柜台和无文字圆钟被一束尘埃光穿过，画面中没有人物",
    palette: ["#B29365", "#6D5047", "#484849", "#141315"], colors: ["暖黄", "低饱和"], compositions: ["三分法", "纵深"], shotSize: "全景",
    lights: ["轮廓光", "低调光"], lightDirection: "侧门缝隙斜射入内", lightQuality: "窄硬光束", subjectPosition: "画面无人", visualFocus: "高处时钟与空柜台上的光带", scenes: ["放映厅"], moods: ["孤独", "怀旧"], time: "夜晚", region: "中国内陆", decade: "2020年代",
    analysis: "售票柜台占据前景，却没有票券、观众或工作人员，功能被完整保留，使用痕迹已经消失。墙上圆钟位于高处亮区，斜光束把它与走廊深处连接，仿佛时间仍在替空间值班。尘埃让光路可见，也把空气的长期静止具体化；大堂不只是空，而是停留在一次永远不会开始的散场前。",
  }),
  frame({
    slug: "cinema-aisle-lamp", filmSlug: "empty-cinema", title: "未灭的引路灯", image: "/images/frames/cinema-aisle-lamp.png",
    alt: "低机位望向空影院中央过道，两侧暗红座椅之间亮着微弱暖色引路灯",
    palette: ["#6C2929", "#B27B3D", "#2A2022", "#09090A"], colors: ["红色", "高对比"], compositions: ["对称", "纵深"], shotSize: "全景",
    lights: ["低调光", "轮廓光"], lightDirection: "过道两侧低位灯", lightQuality: "点状硬光", subjectPosition: "画面无人", visualFocus: "通向银幕的连续暖色光点", scenes: ["放映厅"], moods: ["压抑", "神秘"], time: "夜晚", region: "中国内陆", decade: "2020年代",
    analysis: "低机位把引路灯排列成通往黑暗的微小光点，本应帮助离场的设施却指向无人的银幕。重复座椅维持严格秩序，其中一把没有折回的椅子制造轻微停顿，像缺席观众留下的最后动作。暗红几乎退成棕黑，温度只存在于地面，路径清楚却没有人需要它。",
  }),
  frame({
    slug: "cinema-final-frame", filmSlug: "empty-cinema", title: "银幕熄灭之前", image: "/images/frames/cinema-final-frame.png",
    alt: "空影院的白色银幕仍有微光，放映光束穿过尘埃，后方坐着无清晰面容的虚构放映员",
    palette: ["#B7B8B2", "#4B4547", "#4A2729", "#0A0A0B"], colors: ["黑白", "低饱和"], compositions: ["中心", "留白"], shotSize: "远景",
    lights: ["逆光", "低调光"], lightDirection: "银幕反射光向后方", lightQuality: "大面积柔光与细窄光束", subjectPosition: "人物位于右侧后景边缘", visualFocus: "空白银幕与光束末端的人影", scenes: ["放映厅"], moods: ["孤独", "怀旧"], time: "夜晚", region: "中国内陆", decade: "2020年代",
    analysis: "银幕位于中心并占据最大亮区，却没有任何影像，观众被迫凝视承载内容的空白表面。放映员缩在右侧后景，只由银幕反光勾出肩线，人与机器都让位于最后一段光。大片空座椅建立共同观看的尺度，也让唯一观众的存在更加孤单；熄灭尚未发生，告别已经开始。",
  }),
];
