/* AUTO-GENERATED by 镜间工作台（scripts/studio）—— 已清空：等待第一次回填
 * 在色卡质检台里「采用实测 / 补全」过的画面会写入这里，构建时覆盖 lib/data.ts 里的手写色卡。
 * 手工编辑会被下一次回填覆盖；要撤销某帧，重跑工作台并选择「撤销」。
 */
export const paletteOverrides: Record<string, string[]> = {
};

export const getPaletteOverride = (slug: string): string[] | undefined => paletteOverrides[slug];
